name: 'Format python'
description: 'Runs formatting for the Python project'

inputs:
  working_directory:
    description: 'The working directory where the formatting should be run'
    required: false
    default: '.'

outputs:
  python_format_exit_code:
    description: "The exit code from the python format command"
    value: ${{ steps.python_format.outputs.exit_code }}
  
runs:
  using: "composite"
  steps:
    - name: Install ruff
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      run: |
        pip install ruff
    
    - name: Run Python format
      id: python_format
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      run: |
        set +e
        ruff check --diff --output-format=github .
        EXIT_CODE=$?
        set -e

        echo "exit_code=$EXIT_CODE" >> $GITHUB_OUTPUT