name: 'Setup Python Environment'
description: 'Sets up Python and installs dependencies if requirements.txt exists'

inputs:
  python-version:
    description: 'Version of Python to use'
    required: false
    default: '3.x'
  
runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install dependencies if requirements.txt exists
      shell: bash
      run: |
        if [ -f requirements.txt ]; then
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        fi